0:    N-Human-lovedrome
1:    S-Document-docudrome
2:    W-Project-projectdrome
3:    E-Event-eventodrome

3333: NW-Animal-petodrome
8888: NE-Plant-vegidrome
4:    SW-Machine-machinedrome
5:    SE-Game-gamedrome
