lovedrome: author,autora,autor,speaker,featuring,vía,ponente,madre,padre,hermano,hermana,amiga,amigo,pedalea,compañera,compañero,participa,deportista,ilustrador,ilustradora,coordinado por,jugón,jugona,tío,tía

docudrome: talk,doc,spec,codetail,charla,parte de,parte,obra,trabajo,recommends,post,screencast,recomienda leer,wrote,escribió,recomienda ver,libro,ensayo,aparece en

notedrome: note,reflexion,thought,monolog,dialog,triatlog,conversation,chiste

eventodrome: event,evento,meet,quedada,open,hackathon,hackatón,organiza,colabora con,asistente a

projectdrome: project,proyecto,site,sitio,comisión,depende de,organizador,organizado por,debilitador,ensuciado por,batería en,colabora en,parte del proyecto,proyecto relacionado,ha pedaleado con,vía proyecto,utiliza,usa,movimiento,hosted by,hosting for

gamedrome: juego,creó el juego,jugona de,jugón de,recomienda el juego

petodrome: animal,pet,mascota,anmigo,anmiga

vegidrome: plant,tree,flower,cactus

auidrome: hija,hija,rapaza,rapaz,zagala,zagal
acadodrome: estudiante,becaria,becario
restodrome: maestra,maestro
ripodrome: inspiración
repulsodrome: bug,bicho,debilita,ensucia
# Ejemplo de limitación:
byebyedrome: batería
