# ENTRY PROPERTIES
# * Required:
created_at: Moment when the *auido* was first submitted. REQUIRED property.
auido: Like 'name', just a word or short phrase that we have chosen to remember this entry and whose nature depends on the Drome where its located. REQUIRED property.
# * Optional:
identity: Digital itentity/ies of the owner/s of what this entry represents. OPTIONAL property.
madrino: Indentity/ies of people that think this entry is interesting for others and that know more things about it. OPTIONAL property.

start_living_year: Only for entries into LivingThings Dromes. Year when the entry starts living.
start_living_month: Only for entries into LivingThings Dromes. Month when the entry starts living.
ends_living_year: Only for entries into LivingThings Dromes. Year when the entry pass away.
ends_living_month: Only for entries into LivingThings Dromes. Month when the entry pass away.

# DROME DESCRIPTION
# (different in each drome but the same for all the drome entries)
drome_name:
# Basic info the Drome gives to the user to create new entries
drome_item_name:
drome_item_description:
# Drome qualities:
living_things_drome:

# LIKING DATA (how to fly from here!):
dromes_ports:
property_mappings:

# SEARCH QUERY PROPERTIES:
query: String searched (search request only).
results: Entries that have the query string as part of their names (search request only).
in_other_dromes: Search results in other dromes (search request only).

